# Copyright (c) 2021 Nordic Semiconductor ASA
# Copyright (c) 2025 Intercreate, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 8a72d776c5af6522478155adc91a5f4edb2794e3
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - hal_nxp
          - hal_stm32
          - hal_ti
          - littlefs
          - mbedtls
          - mcuboot
          - zcbor
